[deps]
BDTools = "6f2079fd-6c9e-4521-946b-68ee3d3b6add"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
